### ISSUE TITLE
Create source folders for resources by default

### ISSUE THREAD

**Issue by jmcejuela** [typesafehub/sbteclipse#129]
When I create a new project with _sbteclipse_ I expect to have by default the resources folders (main & test /resources) created. Note that the m2eclipse plugin creates these folders by default too.

In my opinion, having these folders created by default is beneficial for new users who otherwise don't know the typical project structure for sbt or mvn. New users wouldn't have to think where to put their resource files if they needed to. This brings consistency (convention over configuration).

What do you think? Should the resources folders be created by default?

**Comment by benmccann** [comment]
@jmcejuela this is fixed now
