### ISSUE TITLE
nested source directories for play project result in broken eclipse project

### ISSUE THREAD

**Issue by gaydenko** [typesafehub/sbteclipse#165]
sbteclipse, being used in Play project (with subprojects), generates nested source directories, in particular <prj>/test and <prj>/test/resources, resulting in broken eclipse project.

Wasn't lucky to get any feedback in the sbt google group:

https://groups.google.com/forum/#!folder/current/simple-build-tool/MtxS-HXcbzk

**Comment by benmccann** [comment]
This was fixed in 2.5.0 https://github.com/typesafehub/sbteclipse/commit/fae8a812160da5a1f8cdefa190e9ebd566d6b47e

**Comment by gaydenko** [comment]
Great.
