### ISSUE TITLE
Custom repository download issue, still downloading from typesafe repo

### ISSUE THREAD

**Issue by ppatti** [typesafehub/sbteclipse#183]
Hi,

So I have changed the repository settings in my SBT boot/launch properties file to run off of a corporate maven repo which contains all of my dependencies (including sbteclipse plugin). I have also removed any resolver/repo settings from my build.sbt files. All is well (dependencies are being downloaded from my corporate repository) EXCEPT for the sbteclipse core and plugin jars which are still being downloaded from the typesafe repo (http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse). Other plugins defined in the same way (xsbt and sbt-idea plugins) are downloading from my repo correctly, The repo directory structure and ivy pattern in the boot properties match up also.

The eclipse plugin is currently defined in my project's 'project/plugins.sbt' with: addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.2.0") and there are no resolver/repo settings in my sbt files (only in sbt launch properties file and only settings for my corporate repo).

Does this plugin require some special settings to get a custom repo to work, maybe some override in one of my sbt files? It seems strange that I do not have the the typesafe repo defined anywhere in my project and have overridden SBT's default resolvers, yet the plugin is still downloading from that repo.

Any help would be much appreciated. I can also provide more info if needed. Thanks!

**Comment by benmccann** [comment]
It seems like this issue would be in SBT and not sbteclipse's fault, so I'm going to close this. Feel free to file an issue over at the [SBT issue tracker](https://github.com/sbt/sbt/issues) though
