### ISSUE TITLE
Dependency in sbteclipse when using source generators.

### ISSUE THREAD

**Issue by justjoheinz** [typesafehub/sbteclipse#217]
In my build.sbt (sbt 0.13, sbteclipse 2.5.0) I have the following
```
sourceGenerators in Compile += Def.task {
  import SimplezGenerator._
  val result : Seq[(String, String)] = makeSomeSources()
  result.map{case (name, content) =>
    val file = (sourceManaged in Compile).value / "simplez" / name
    IO.write(file, content)
    file
  }
}.taskValue

EclipseKeys.createSrc := EclipseCreateSrc.Default + EclipseCreateSrc.Managed
```

Unfortunately I need to tell sbteclipse to put the managed sources in the classpath. How can I achieve the same, whilst not making sbteclipse a plugin dependency of my project and keep it in the global ~/.sbt/0.13 definition? I would prefer not to include IDE artifacts in the project. Hopefully sbteclipse could figure out on its own, that there are managed resources in the project and add them to the classpath.

**Comment by benmccann** [comment]
sbteclipse 4.0.0-RC1 will puts managed sources on your classpath by default
