### ISSUE TITLE
Problems with-source=true with cached resolution

### ISSUE THREAD

**Issue by nightscape** [typesafehub/sbteclipse#234]
sbteclipse and the newly introduced (SBT 0.13.7)
```
updateOptions := updateOptions.value.withCachedResolution(true)
```
don't seem to cooperate.
I've modified the ```03-sbt-dependency-withsources``` test case to expose the problem here:
https://github.com/nightscape/sbteclipse/tree/cached-resolution-problems

scripted tests are green [after updating to SBT 0.13.7](https://github.com/nightscape/sbteclipse/commit/5a5928da175ccfae940dc9f88f1c38abd5aa140f) and start to fail when [enabling cached resolution](https://github.com/nightscape/sbteclipse/commit/7b1822135619e8326d34cc8fb4f983f064ba31a2).

**Comment by jsuereth** [comment]
i believe this is an issue in updateClassifiers + cached resolution, not with this particular plugin.  We're still working on fixing that, but I'm clsoing this issue as you have a link already.
