### ISSUE TITLE
Properly export a Scala 2.10 project for Scala IDE 4.0

### ISSUE THREAD

**Issue by dotta** [typesafehub/sbteclipse#239]
The latest and greatest Scala IDE 4.0 supports both Scala 2.10 and 2.11 projects. However, to
correctly configure a Scala 2.10 project in Eclipse, the following project's settings need to be set in `.settings/org.scala-ide.sdt.core.prefs`:

```
scala.compiler.additionalParams=-Xsource:2.10 -Ymacro-expand:none
scala.compiler.sourceLevel=2.10
```

And, of course, we should also make sure that ``scala.compiler.useProjectSettings=true`` is set.

**Comment by matanster** [comment]
What's actually the status of this matter now?
Is `sbt -with-bundled-scala-containers=false eclipse` still supposed to work as documented in
http://scala-ide.org/blog/Xsource-compatibility.html? I was not having a lot of luck with it today.
