### ISSUE TITLE
Generate classes managed only when needed

### ISSUE THREAD

**Issue by benmccann** [typesafehub/sbteclipse#254]
@jsuereth I can't figure out how to do this

Right now as a default, we have:

    EclipseKeys.generateClassesManaged in scope := true

It'd be much better to generate only when needed instead of always:

    EclipseKeys.generateClassesManaged in scope := EclipseKeys.createSrc.value contains EclipseCreateSrc.ManagedClasses

This doesn't work. I get a message "References to undefined settings". Any ideas how to accomplish this?

**Comment by jsuereth** [comment]
```scala
EclipseKeys.generateClassesManaged in scope := 
   EclipseKeys.createSrc.?.value match {
       case Some(cs) => cs contains EclipseCreateSrc.ManagedClasses
       case None => false
   }
```

The `?` method takes a `Key[T]` and makes it an `Key[Option[T]]` where if the setting is undefined you get `None`, otherwise you get `Some(T)`.

**Comment by benmccann** [comment]
After discussing over chat, EclipseKeys.createSrc has a default value. I think the problem is that we're referencing it before the default it set. The reason for this likely is that it's actually doing this dumb thing where it looks up the value on the build and if it doesn't exist it provides a default, rather than setting a default directly in the settings

**Comment by benmccann** [comment]
Here's a branch for fixing the way we set the default settings as suggested by @jsuereth : https://github.com/typesafehub/sbteclipse/tree/settings-cleanup

It causes errors right now when you run the scripted tests. @jsuereth suggested this might be because plugin only gets applied to projects with the JvmPlugin, so we should skip non-JVM projects. The initial idea for doing this was to update the skip method in Eclipse.scala to check for the EclipsePlugin:

    def skip(ref: ProjectRef, project: ResolvedProject, skipParents: Boolean, state: State): Boolean =
      !(project.autoPlugins contains EclipsePlugin) || skip(ref, state) || (skipParents && !project.aggregate.isEmpty)

However, when I do this, it causes the scripted tests to fail.

**Comment by benmccann** [comment]
This is done now
