### ISSUE TITLE
Release 4.0.0 (or 4.0.0-RC0)

### ISSUE THREAD

**Issue by benmccann** [typesafehub/sbteclipse#258]
@jsuereth ready for a new release now! Thanks again very much for all the help!

**Comment by benmccann** [comment]
CC @corruptmemory. When you migrate this to bintray, can you cut a new release of the plugin?

**Comment by corruptmemory** [comment]
ebteclipse 4.0.0-RC1 has been published to bintray: https://bintray.com/sbt/sbt-plugin-releases/sbteclipse/view.  If you're happy this issue can be marked closed.

**Comment by benmccann** [comment]
Thanks!
