### ISSUE TITLE
sbteclipse shouldn't touch .gitignore

### ISSUE THREAD

**Issue by dotta** [typesafehub/sbteclipse#271]
I'm using 4.0.0-RC2 and noticed that sbteclipse is creating a .gitignore when it's run. IMO, this should not be the default behavior, as adding a .gitignore for every module in a multi-module project is not what I want.

If useful at all, it would be better to have this functionality behind a flag. Furthermore, the .gitignore's content should be:
```
# Scala-IDE specific
.scala_dependencies
.project
.settings
.cache-main
.cache-tests
bin
```

And not just the `bin` folder, as it currently is.

**Comment by dotta** [comment]
Guys, I'm really sorry for blaming sbteclipse for this issue. I was actually going to fix it myself, and realised sbteclipse doesn't create and neither touches the projects' .gitignore.

In fact, the component to blame is either the Scala IDE (what in hell :-)) or maybe the EGit Eclipse plugin.  I'll keep digging, but there is nothing that needs to be changed in sbteclipse. Sorry again.

**Comment by dotta** [comment]
I confirm the behaviour I described is due to Egit Eclipse plugin (and there is actually an option for disabling it).

I'm letting @dragos know as he was also annoyed by this, and the Scala IDE SDK bundles Egit, which means this issue may be experienced by quite a few people out there - I'd almost go as far as removing the Egit plugin from the Scala IDE SDK (yep, that's how much I hate that feature :-)).

**Comment by dragos** [comment]
Any link to that "feature"? :)

**Comment by dotta** [comment]
Eclipse > Preferences > Team > Git > Projects > "Automatically ignore derived resources by adding them to .gitignore"
