### ISSUE TITLE
Ignoring TwirlKeys.templateImports in build.sbt

### ISSUE THREAD

**Issue by AmirKarimi** [typesafehub/sbteclipse#283]
I used `TwirlKeys.templateImports` in `build.sbt` like this:

```
TwirlKeys.templateImports ++= Seq(
  "reactivemongo.bson.{BSONObjectID, BSONDocument}",
  "models.contents._",
  "api.contents._",
  "reactivemongo.api.gridfs.ReadFile")
```

But Scala IDE ignores them and reports not found errors in play template files. The errors will be fixed by adding those imports in project settings manually (Project Properties -> Play2 -> New...).

Eclipse: 4.1.0-vfinal-20150525-1102-Typesafe
Scala IDE for Eclipse: 4.1.0.v-2_11-201505250839
Scala 2.11.6: 4.1.0.201505250838
Play2 support in Scala IDE: 0.4.6.v-2_11-201505250858

**Comment by benmccann** [comment]
What version of sbteclipse? Are you sure this is a bug in sbteclipse?

**Comment by AmirKarimi** [comment]
sbteclipse version is 3.0.0. Actually I [posted](https://github.com/scala-ide/scala-ide-play2/issues/245) this issue for scala-ide-play2 project but no body replied.

I think it would be another solution to add template imports in project settings file at `.settings/org.scala-ide.play2.prefs` like this:

```
eclipse.preferences.version=1
templateImports=import reactivemongo.bson.{BSONObjectID, BSONDocument}\nimport models.contents._\nimport api.contents._\nimport reactivemongo.api.gridfs.ReadFile\n
```

I'm not sure if it's possible to be supported by Scala IDE but this is another solution which I think is possible. However we need to run sbteclipse after changing build.sbt.

**Comment by benmccann** [comment]
I'd suggest upgrading to Play 2.4 and sbteclipse 4.0.0. There were some problems in earlier versions.

That being said, there's no information here that leads me to believe there's any bug in sbteclipse

I don't mean to be unhelpful by closing this, but this really seems like a problem in ScalaIDE
