### ISSUE TITLE
`EclipseKeys.withSource in ThisBuild` is ignored (4.0.0 regression from 3.0.0)

### ISSUE THREAD

**Issue by Blaisorblade** [typesafehub/sbteclipse#296]
I have a multi-project build, and set 
```
EclipseKeys.withSource in ThisBuild := true
```
in [the main build.sbt](https://github.com/inc-lc/ilc-scala/blob/master/build.sbt#L105). If I switch from 2.5.0 to 4.0.0, that stops working, because of the `in ThisBuild` part — somehow I need to set that per project. 3.0.0 is safe. Has that got anything to do with AutoPlugin?

**Comment by Blaisorblade** [comment]
I think I found it — defaults are set per-project through `projectSettings`, so override per-build settings, as visible [here](https://github.com/typesafehub/sbteclipse/blob/v4.0.0/src/main/scala/com/typesafe/sbteclipse/core/EclipsePlugin.scala#L42-L52).

[SBT guidelines](http://www.scala-sbt.org/0.13/docs/Plugins.html) suggest defaults should be in globalSettings, to have the least priority.

[The history](https://github.com/typesafehub/sbteclipse/commit/b6b0379ef9b9c9602a77b7dc09fb1c2bf25b8610#diff-e127bb09dd9d0b8de01cd7be195d59bcR32) shows no reason why `settings` was originally converted to `projectSettings` — later, some settings were moved to buildSettings.

**Comment by Blaisorblade** [comment]
So, switching the default to `buildSettings` already fixed my local issue. Can I prepare a PR switching all those defaults to `globalSettings` (as recommended)? @benmccann, since you did the original conversion, is there any reason I'm missing?

Disclaimer: I haven't restudied all details of delegation — they're so much that I forget them anyway quickly. It makes sense to me that defaults should have the lowest priority and that's `globalSettings`, but that's as much as I know.

**Comment by benmccann** [comment]
I don't really understand the difference between any of these. I'd need some more explanation. I'll probably defer to @jsuereth on this one

**Comment by mlangc** [comment]
Hmm, sorry if I didn't get this, but is there a suggested workaround till this is handled properly?

**Comment by Blaisorblade** [comment]
I'd suggest:
1. Sticking with version 3.0.0 — I think that's what I did.
2. If that fails somehow, set `EclipseKeys.withSource := true` for each project.
Does any of that work for you?

Meanwhile I've pinged maintainers to merge the fix (#300).

**Comment by mlangc** [comment]
Yes, thanks, both 1. and 2. work for me... I just wondered if there are other workarounds.
