### ISSUE TITLE
Incompatible with sbt-ensime and/or coursier

### ISSUE THREAD

**Issue by dragos** [typesafehub/sbteclipse#325]
It looks like the scalaz dependency (7.2.5) is binary incompatible with the one used by coursier and sbt-ensime (7.2.7).

```
[error] ({.}/*:ensimeScalaJars) java.lang.NoSuchMethodError: scalaz.EitherT.orElse(Lscala/Function0;Lscalaz/Bind;)Lscalaz/EitherT;
[error] Missing task key: ensimeScalaJars
java.lang.IllegalArgumentException
```

**Comment by benmccann** [comment]
I just bumped the scalaz version: https://github.com/typesafehub/sbteclipse/commit/f7a61d2bd78a55096b18822f6280d6ad5319a995

I'm not sure why you would have had any trouble though. sbteclipse seems to work just fine with 7.2.7 without any changes. And 7.2.7 should evict 7.2.5, so having an older version shouldn't affect coursier or sbt-ensime
