### ISSUE TITLE
Bump Scalaz Version to 7.2.8 (Coursier broken)

### ISSUE THREAD

**Issue by godenji** [typesafehub/sbteclipse#333]
Coursier and Sbt-Eclipse are periodically out of sync wrt to used scalaz version; the end result is that the two plugins cannot be used togther, or one has to revert to an older version with matching scalaz dependency.

For example, sbt-eclipse 5.0.1 and coursier 1.0.0-M14 have both depend on scalaz 7.2.5, while sbt-eclipse latest (5.1.0) depends on scalaz 7.2.7, and coursier latest (M15) depends on scalaz 7.2.8, which seems to break binary compatibility.

Not sure how to resolve this other than to keep the projects' scalaz versions in sync.

**Comment by benmccann** [comment]
If you send a pull request I can merge it :-)

**Comment by godenji** [comment]
Done

--Noah

Noah Cutler
Tech Lead
New Mind Development
www.newmindit.com
