### ISSUE TITLE
sbt 1.0.0 compatible plugin

### ISSUE THREAD

**Issue by pjfanning** [typesafehub/sbteclipse#343]
Are there plans to release an sbt 1.0.0 compatible plugin?

**Comment by benmccann** [comment]
If someone sends a pull request. I probably won't have time otherwise

**Comment by mkurz** [comment]
What would have to be done?

**Comment by benmccann** [comment]
Somone just sent me a PR for sbt-avro if you want to use it as an example: https://github.com/sbt/sbt-avro/commit/be9a0357eb9a3fdd38ca93cfc956348682daa896

**Comment by benmccann** [comment]
Huge thanks to @godenji for this! Fixed via https://github.com/typesafehub/sbteclipse/pull/345
