### ISSUE TITLE
feature request: need a way to specify an alternative default build files directory

### ISSUE THREAD

**Issue by philwalk** [typesafehub/sbteclipse#352]
Many projects include a 'bin' directory, typically containing shell scripts related to the project.  Unfortunately, the default value for the build output files directory is also 'bin', with the result that after issuing "sbt eclipse", the next subsequent "clean" from within the Eclipse Run menu will delete this directory, including potentially edited but not-yet-checked-in changes. 

Some projects have started including a warning in user documentation (see for example [http://dotty.epfl.ch/docs/contributing/eclipse.html](http://dotty.epfl.ch/docs/contributing/eclipse.html).

Two suggestions, either of which would reduce this risk:

1. change the default directory from "bin" to "classes" (or "build"?)
2. allow the default directory to be managed with an environment variable, or other project-specific configuration

There appear to be exactly four references to the string literal "bin" in the project:

```
src/main/scala-sbt-0.13/com/typesafe/sbteclipse/core/Eclipse.scala:  (Seq("bin") map EclipseClasspathEntry.Output)
src/main/scala-sbt-1.0/com/typesafe/sbteclipse/core/Eclipse.scala:   (Seq("bin") map EclipseClasspathEntry.Output)
src/sbt-test/sbteclipse/02-contents/tasks.sbt:                       if (!(classpath.child contains <classpathentry kind="output" path="bin"/>))
src/sbt-test/sbteclipse/02-contents/tasks.sbt:                       error("""Expected .classpath of root project to contain <classpathentry kind="output" path="bin"/> """)
```

Thanks for considering this. I would be happy to do a pull request and provide a proposed fix for your review.

**Comment by benmccann** [comment]
There's an `eclipseOutput` setting which controls this: https://github.com/typesafehub/sbteclipse/wiki/Using-sbteclipse

**Comment by philwalk** [comment]
The eclipseOutput doesn't solve this particular problem, though I now realize that my description above is not quite sufficient.   The entry in the generated .classpath file that causes the grief is this one:
```
<classpathentry kind="output" path="bin"/>
```
and AFAICT, the "bin" setting is hard-wired in Eclipse.scala near line 312

whereas the eclipseOutput setting lets me control these entries, but they aren't causing the problem:
```
  <classpathentry output=".target" kind="src" path="src\main\scala"/>
  <classpathentry output=".target" kind="src" path="target\scala-2.12\src_managed\main"/>
  <classpathentry output=".target" kind="src" path="src\test\scala"/>
```

**Comment by benmccann** [comment]
That seems like a bug. I believe it should use the `eclipseOutput` setting instead of a hard-coded `bin` directory. But the default value for `eclipseOutput` should be `bin`

**Comment by benmccann** [comment]
dotty is open to changing the name of their scripts directory in case you want to submit a PR there https://github.com/lampepfl/dotty/issues/3401. We should still fix this issue because the `eclipseOutput` setting should be made to work, but I think that it'd also be nice if they didn't use the `bin` directory so that you didn't need to change the default settings

**Comment by philwalk** [comment]
I would prefer that dotty not change the name of their scripts directory,
as it follows a decades old standard and many developers are familiar with
it.  Below my eclipse workspace, there are 82 .git directories and 121
'bin' directories.   This is the only project I'm familiar with that uses
'bin' as the binary output directory.  Much more common would be 'classes',
'build', or 'target'.  If it weren't already legacy behavior, I would favor
changing the sbteclipse default.

**Comment by benmccann** [comment]
We did not choose `bin` as the output directory. That's what eclipse has always used by default, so we're just matching that here.

Anyway, pull requests welcome if you'd like to send a fix to remove the hardcoded `bin`. I've been merging community PRs, but unfortunately don't have time to work on the project myself.

**Comment by philwalk** [comment]
ah, thanks for the reminder, I had forgotten that "bin" is the Eclipse default.   I have no experience with sbt plugin development, is there a contributors guide you can recommend?  I see lots of files below `src/test` but haven't figured out how to run the tests just yet, any suggestions are welcome.

**Comment by benmccann** [comment]
I don't have any pointers ready, but let me know if you have questions. If you run `sbt scripted` it will run the tests.

**Comment by philwalk** [comment]
after experimenting for a few days, I have come to some tentative conclusions, although I'm happy to be corrected if I'm off base.

1. it's hard to figure out a use-case for the `eclipseOutput` setting in which it does not take the same value as the `target` setting
2. I can't see a simple or clean way from within Eclipse.scala to determine the values of project settings such as `target`
3. eclipse projects that use this plugin, being sbt based, will typically (always?) expect build files to reside in the directory directory referenced by the `target` setting

If there's a reasonable way to determine the value of the project `target` setting from within this plugin, I would be willing to create a pull request that changes the default value of the output directory from "bin" to the project `target` value.   I'm also open to other suggestions.

I noticed, BTW, that the output directories of scripted subprojects (e.g., suba, subb, subc) are ALWAYS named target, regardless of the value of either the plugin `eclipseOutput` setting or the client project `target` setting, as these only seem to be configurable at the top level of the project.   For that reason (and assuming that this conclusion is correct), it might be worth considering the simple expedient of changing  "bin" to "target" on line 312 of Eclipse.scala

As I said, I'm open to suggestions, including to close this issue with no changes.

**Comment by benmccann** [comment]
The `target` setting you're referring to - is that the setting which controls the directory that SBT sends compilation output to (typically the `target directory`)? If so, you absolutely do not want `eclipseOutput` to be the same as `target`. We had that as the default a few years ago and it caused no end of trouble for people. You'd end up with all kinds of weird problems where the SBT compilation output and Eclipse compilation output are being sent to the same place and stomping on each other. It works much better to make these separate directories. I think someone would need to setup an integration between sbt server and  [LSP4E](https://projects.eclipse.org/projects/technology.lsp4e) in order to have only a single output directory.

**Comment by philwalk** [comment]
Yes, I was referring to the `target` setting, which defaults to "target".   I'll take your word that problems would ensue, in practice I usually set it to "eclipse-target", although I have a script that edits the generated `.classpath` file, replacing the generated `bin` value to avoid accidentally deleting the "bin" directory,  (the problem I described above.).   Perhaps we can change the default from "bin" to something that's unlikely to collide with client files?

**Comment by benmccann** [comment]
`bin` is the default that Eclipse has used for many years, so I'm hesitant to change it. If you create a new Eclipse project it will create a bin directory for you. I think it would be confusing to Eclipse users to call it something else. But we should make it easy to change on a per-project basis - it seems that's broken right now

**Comment by philwalk** [comment]
I created a PR, but I'm sure it's bogus, it unexpectedly seems to already have changes to merge (not my intention).   Not sure how to recover or proceed from here ...

**Comment by philwalk** [comment]
submitted a PR for this, thanks for all the assistance!
It would be nice if a warning could be issued when settings `eclipseOutput` and `target` refer to different directories, although it's not clear to me how to access the value of the `target` setting from within Eclipse, so that's for later if at all.

**Comment by benmccann** [comment]
I'll release 5.2.4 with your fix
